# Puppetfile
# Configuration for librarian-puppet. For example:
#
forge "https://forgeapi.puppetlabs.com"
mod "puppetlabs/stdlib"
mod "puppetlabs/java"
mod "puppetlabs/mysql", "2.3.1"
mod "razorsedge/cloudera"
mod "stankevich/python"
mod "cesnet/hadoop"
mod "cesnet/hbase"
mod "cesnet/hive"
mod "cesnet/zookeeper"
mod "kupferk/osfixes"

